SET IDENTITY_INSERT [dbo].[Options] ON
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (1, N'Morala trebuie fundamentată pe premise transcendentale.', 0, 1)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (2, N'Morala poate fi dedusă din premisele existenței lui Dumnezeu și a omului ca ființă rațională.', 1, 1)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (3, N'Morala trebuie să se bazeze pe valori subiective.', 2, 1)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (4, N'Morala este un construct social și cultural.', 3, 1)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (5, N'Consideră că ierarhia valorilor este o realitate fundamentală și legitimă.', 0, 2)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (6, N'Susține că valorile morale sunt deduse din principii transcendente.', 1, 2)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (7, N'Argumentează că ierarhia valorilor este un fapt lipsit de legitimitate și fundament.', 2, 2)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (8, N'Consideră că valorile morale trebuie impuse prin autoritate coercitivă.', 3, 2)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (9, N'Omul slab este acela care își asumă viața în întregime, fără restricții.', 0, 3)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (10, N'Omul slab este acela care are puterea de a-și impune voința asupra altora.', 1, 3)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (11, N'Omul slab este acela care își ascunde neputința și încearcă să domine pe cei puternici prin moralitate.', 2, 3)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (12, N'Omul slab este acela care nu își dorește fericirea și se conformează doar cu suferința.', 3, 3)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (13, N'Consideră că toate modalitățile sunt morale și constructive.', 0, 4)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (14, N'Susține că modalitățile sunt lipsite de moralitate și sunt esențial imorale.', 1, 4)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (15, N'Argumentează că convertirea la moralitate este imposibilă din punct de vedere moral.', 2, 4)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (16, N'Crede că convertirea la moralitate trebuie să fie impusă prin constrângere fizică.', 3, 4)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (17, N'Crede că omul poate obține fericirea prin urmarea unor principii morale rigide.', 0, 5)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (18, N'Argumentează că omul nu poate obține fericirea și este condamnat să sufere mereu.', 1, 5)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (19, N'Consideră că omul trebuie să își asume responsabilitatea pentru fericirea sa.', 2, 5)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (20, N'Susține că omul nu știe calea spre fericire, dar nu poate renunța la ea.', 3, 5)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (21, N'Compară procesul de deducție morală cu procesul de învățare a unei limbi străine.', 0, 6)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (22, N'Analogia dintre deducția morală și deducția matematică, în care premisele clare conduc la concluzii incontestabile.', 1, 6)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (23, N'Comparația dintre deducția morală și interpretarea textelor religioase.', 2, 6)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (24, N'Analogia dintre deducția morală și procesul de instruire într-o artă sau meserie.', 3, 6)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (25, N'Argumentează că premisele clare și conceptele înțelese de mintea umană pot conduce la deducții morale necesare și incontestabile.', 0, 7)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (26, N'Afirmă că moralitatea este subiectivă și că nu poate fi tratată ca o știință exactă.', 1, 7)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (27, N'Consideră că moralitatea este exclusiv o chestiune de tradiție și convenție socială.', 2, 7)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (28, N'Crede că moralitatea este dictată de instinctele umane și nu poate fi explicată rațional.', 3, 7)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (29, N'Consideră că nedreptatea este o consecință inevitabilă a existenței proprietății private.', 0, 8)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (30, N'Afirmația că „unde nu există proprietate, nu există nedreptate” este la fel de certă ca o demonstrație matematică.', 1, 8)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (31, N'Susține că conceptul de proprietate este relativ și poate varia în funcție de normele sociale.', 2, 8)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (32, N'Concluzionează că ideea de nedreptate este inextricabil legată de ideea de proprietate și că ele sunt sinonime.', 3, 8)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (35, N'Argumentarea necesității unei justificări morale bazate pe rațiune și existența unei ființe supreme.', 0, 9)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (36, N'Critica relativismului moral și susținerea existenței unor adevăruri morale absolute.', 1, 9)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (37, N'Demonstrarea posibilității de a deduce regulile morale din premise clare, la fel ca în matematică.', 2, 9)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (38, N'Expunerea ideii că moralitatea este un construct social fără fundament în realitatea obiectivă.', 3, 9)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (39, N'Observarea comportamentului uman în societate.', 0, 10)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (40, N'Deducerea moralității din religie și tradiție.', 1, 10)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (41, N'Adoptarea unor reguli și norme impuse de autorități.', 2, 10)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (42, N'Examinarea ideilor despre o ființă supremă și despre natura umană rațională.', 3, 10)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (43, N'Susține că regulile de bună-cuviință sunt esențiale pentru menținerea unei societăți armonioase și echitabile.', 0, 11)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (44, N'Consideră că egalitatea între indivizi este un principiu fundamental al societății și al vieții în general.', 1, 11)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (45, N'Argumentează că aplicarea excesivă a acestor principii poate duce la decădere și descompunere socială.', 2, 11)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (46, N'Crede că principiile de bună-cuviință și egalitatea sunt esențiale pentru evoluția și progresul societății.', 3, 11)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (47, N'Consideră că voința de putere este un concept moral, care trebuie să fie îmbrățișat de către fiecare individ.', 0, 12)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (49, N'Argumentează că voința de putere este esența vieții și a societății, determinând acțiunile și interacțiunile umane.', 1, 12)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (50, N'Susține că voința de putere trebuie să fie reglementată de reguli și norme morale.', 2, 12)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (51, N'Crede că voința de putere este un concept abstract și irelevant pentru societate.', 3, 12)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (52, N'Argumentează că exploatarea este o funcție organică fundamentală a vieții și a voinței de putere.', 0, 13)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (53, N'Consideră că exploatarea este o practică imorală care trebuie să fie eliminată din societate.', 1, 13)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (54, N'Susține că exploatarea este o caracteristică a societăților primitive și corupte.', 2, 13)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (55, N'Crede că exploatarea este necesară pentru menținerea echilibrului social.', 3, 13)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (56, N'Crede că factorul primordial al istoriei este dezvoltarea morală a oamenilor.', 0, 14)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (57, N'Argumentează că factorul primordial al istoriei este lupta pentru supremație și voința de putere.', 1, 14)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (58, N'Susține că factorul primordial al istoriei este evoluția tehnologică și științifică.', 2, 14)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (59, N'Consideră că factorul primordial al istoriei este religia și credința în divinitate.', 3, 14)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (60, N'Argumentează că exploatarea trebuie să fie reglementată prin norme morale pentru a evita abuzurile.', 0, 15)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (61, N'Susține că exploatarea este un fenomen recent și că trebuie eradicată din societate.', 1, 15)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (62, N'Crede că voința de putere și exploatarea sunt fenomene morale condamnabile și trebuie eliminate.', 2, 15)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (63, N'Consideră că voința de putere și exploatarea sunt inevitabile și esențiale pentru viață și societate.', 3, 15)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (64, N'Toți oamenii își doresc să devină dumnezei pentru a atinge fericirea absolută.', 0, 16)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (65, N'Există o tendință universală de a căuta fericirea, indiferent de vârstă sau statut social.', 1, 16)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (66, N'Oamenii sunt complet satisfăcuți cu condiția lor și nu caută niciodată fericirea.', 2, 16)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (67, N'Dorința de fericire este un sentiment relativ rar întâlnit în rândul oamenilor.', 3, 16)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (68, N'Unii caută fericirea în autoritate, alții în cercetări și științe, iar alții în plăceri pământești.', 0, 17)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (69, N'Toți oamenii caută fericirea exclusiv în plăceri pământești.', 1, 17)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (70, N'Nimeni nu caută fericirea în exteriorul lor, ci doar în propriul sine.', 2, 17)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (71, N'Majoritatea oamenilor caută fericirea în conformitate cu regulile stoicilor.', 3, 17)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (72, N'Fericirea poate fi găsită doar prin renunțarea la rațiune și adoptarea unui stil de viață animalic.', 0, 18)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (73, N'Căutarea fericirii în exterior, prin divertisment și plăceri, este inutilă din cauza bolilor și a conflictelor interioare.', 1, 18)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (74, N'Singura cale de a atinge fericirea este să devii un dumnezeu sau să renunți la rațiune și să devii o ființă irațională.', 2, 18)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (75, N'Fericirea nu poate fi găsită în afara sau în interiorul nostru, ci doar în Dumnezeu.', 3, 18)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (76, N'Consideră că eforturile umane sunt inutile și conduc doar la incertitudine și nefericire.', 0, 19)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (77, N'Susține că eforturile umane sunt complet satisfăcătoare și aduc întotdeauna adevărul și fericirea dorită.', 1, 19)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (78, N'Crede că fericirea poate fi atinsă prin distracție și divertisment.', 2, 19)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (79, N'Argumentează că fericirea poate fi atinsă prin cunoaștere științifică și autoritate.', 3, 19)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (80, N'Examinarea diferitelor teorii etice despre fericire.', 0, 20)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (81, N'Analiza diverselor forme de distracție și divertisment.', 1, 20)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (82, N'Căutarea sensului vieții și a fericirii umane.', 2, 20)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (83, N'Explorarea conceptului de virtute și moralitate.', 3, 20)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (84, N'Eudaimonia şi arte.', 0, 21)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (85, N'Fericirea şi convenţiile sociale.', 1, 21)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (86, N'Eudaimonia şi arete.', 2, 21)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (87, N'Virtutea şi cunoaşterea binelui în sine.', 3, 21)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (88, N'Puterea şi autoritatea.', 0, 22)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (89, N'Virtutea şi cumpătarea.', 1, 22)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (90, N'Cunoaşterea binelui în sine.', 2, 22)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (91, N'Respectarea convenţiilor sociale.', 3, 22)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (92, N'Inteligența și modestia.', 0, 23)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (93, N'Generozitatea și prietenia.', 1, 23)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (94, N'Onestitatea și perseverența.', 2, 23)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (95, N'Curajul, cumpătarea, înţelepciunea și dreptatea.', 3, 23)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (96, N'Fericirea este definită de puterea şi autoritatea unei persoane.', 0, 24)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (97, N'Fericirea este obţinută prin respectarea convenţiilor sociale.', 1, 24)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (98, N'Fericirea este activitatea sufletului în conformitate cu virtutea.', 2, 24)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (99, N'Fericirea este exclusiv o chestiune de circumstanțe exterioare.', 3, 24)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (100, N'Ca și calea extremă între prea mult şi prea puţin.', 0, 25)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (101, N'Ca excepţii de la regulile convenţiilor sociale.', 1, 25)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (102, N'Ca și caracteristici inerente persoanei, indiferent de obişnuinţă.', 2, 25)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (103, N'Ca virtuţi raţionale, care se învaţă prin obişnuință.', 3, 25)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (104, N'Plăcerile și durerile.', 0, 26)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (105, N'Cunoașterea.', 1, 26)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (106, N'Temerile.', 2, 26)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (107, N'Moneda reală.', 3, 26)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (108, N'Curajul.', 0, 27)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (109, N'Dreptatea.', 1, 27)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (110, N'Cumpătarea.', 2, 27)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (111, N'Virtutea autentică.', 3, 27)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (112, N'Virtutea.', 0, 28)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (113, N'Plăcerile.', 1, 28)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (114, N'Durerile.', 2, 28)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (115, N'Temerile.', 3, 28)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (116, N'Plăcerile și durerile.', 0, 29)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (117, N'Cunoașterea.', 1, 29)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (118, N'Temerile.', 2, 29)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (119, N'Curajul, cumpătarea și dreptatea.', 3, 29)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (120, N'Este pură și autentică.', 0, 30)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (121, N'Este grea de obținut.', 1, 30)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (122, N'Este lipsită de valoare.', 2, 30)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (123, N'Este destinată numai sclavilor.', 3, 30)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (124, N'Bogăția.', 0, 31)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (125, N'Flautul și instrumentul.', 1, 31)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (126, N'Fericirea.', 2, 31)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (127, N'Recreația.', 3, 31)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (128, N'Este dorită numai în vederea altor bunuri.', 0, 32)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (129, N'Este obținută prin satisfacție.', 1, 32)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (130, N'Este scopul final pentru alte activități.', 2, 32)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (131, N'Este dorită pentru ea însăși.', 3, 32)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (132, N'Satisfacția pe care o aduc.', 0, 33)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (133, N'Plăcerea rezultată din ele.', 1, 33)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (134, N'Acțiunea în sine.', 2, 33)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (135, N'Recunoașterea publică.', 3, 33)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (136, N'Jocul și gluma sunt scopuri în sine.', 0, 34)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (137, N'Jocul este necesar pentru recreație.', 1, 34)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (138, N'Osteneala și suferința vieții nu ar avea sens în contextul jocului.', 2, 34)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (139, N'Jocul și gluma sunt contradictorii cu munca serioasă.', 3, 34)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (140, N'Este o viață de muncă serioasă.', 0, 35)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (141, N'Este o viață de jocuri vesele.', 1, 35)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (142, N'Este o viață de satisfacții plăcute.', 2, 35)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (143, N'Este o viață de recreație continuă.', 3, 35)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (144, N'Bucuria de a trăi în lux și bogăție.', 0, 36)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (145, N'Bucuria de a se bucura de plăceri efemere.', 1, 36)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (146, N'Bucuria de adevăr și de a fi în comuniune cu Dumnezeu.', 2, 36)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (147, N'Bucuria de a experimenta senzații intense și extrem de plăcute.', 3, 36)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (148, N'Oamenii doresc să fie înșelați pentru a obține beneficii personale.', 0, 37)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (149, N'Oamenii nu doresc să fie înșelați, ci caută întotdeauna adevărul și fericirea.', 1, 37)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (150, N'Oamenii doresc să fie cinstiți pentru a atinge adevărul și fericirea.', 2, 37)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (151, N'Oamenii sunt indiferenți cu privire la a fi înșelați sau cinstiți.', 3, 37)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (152, N'Viața fericită este însăși bucuria de adevăr și de a fi în comuniune cu Dumnezeu.', 0, 38)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (153, N'Viața fericită este opusă adevărului și nu îl include deloc.', 1, 38)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (154, N'Viața fericită este bazată pe iluzii și nu are legătură cu adevărul.', 2, 38)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (155, N'Viața fericită este independența totală față de orice adevăr sau realitate.', 3, 38)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (156, N'Oamenii sunt fericiți, dar nu își dau seama de asta.', 0, 39)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (157, N'Oamenii sunt preocupați mai mult de lucrurile care îi fac nefericiți decât de cele care îi fac fericiți.', 1, 39)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (158, N'Oamenii nu sunt fericiți pentru că nu își doresc să cunoască adevărul.', 2, 39)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (159, N'Oamenii nu sunt fericiți pentru că nu au acces la plăcerile lumii materiale.', 3, 39)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (160, N'Să ne concentram exclusiv pe plăcerile lumii materiale.', 0, 40)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (161, N'Să ne bucurăm de iluziile și jocurile lumii.', 1, 40)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (162, N'Să ne înțelegem și să ne amintim slăbiciunile.', 2, 40)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (163, N'Să ne apropiem de Dumnezeu și de adevăr.', 3, 40)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (164, N'Moartea este definitivă și aduce sfârșitul existenței.', 0, 41)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (165, N'Moartea este un popas de odihnă înaintea Nemuririi și este transfigurată prin speranța celei de-a doua veniri.', 1, 41)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (166, N'Moartea este un fenomen evanescent, fără nicio semnificație spirituală.', 2, 41)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (167, N'Moartea este o condamnare definitivă la neant și disperare.', 3, 41)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (168, N'O promovare a valorilor economice și materiale în fața celor spirituale.', 0, 42)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (169, N'O exaltare a păcătosului și a bogatului în fața dreptului.', 1, 42)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (170, N'O inversare a valorilor lumii vechi, în care dreptul și umilința sunt promovate.', 2, 42)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (171, N'O întărire a ierarhiei sociale și economice existente.', 3, 42)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (172, N'Moartea este învinsă și transformată într-un popas de odihnă înaintea Nemuririi, iar viața devine mai plenară și mai victorioasă.', 0, 43)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (173, N'Viața și moartea sunt două aspecte separate și opuse.', 1, 43)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (174, N'Viața și moartea sunt echivalente și nu au nicio semnificație distinctă.', 2, 43)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (175, N'Moartea este inevitabilă și finală, iar viața este un proces efemer și lipsit de sens.', 3, 43)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (176, N'O consolidare a structurilor sociale și economice existente.', 0, 44)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (177, N'O încurajare a inegalității și a injustiției sociale.', 1, 44)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (178, N'O promovare a unei economii materiale și materialiste.', 2, 44)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (179, N'O întărire a vieții și a speranței prin triumful asupra morții și a întunericului.', 3, 44)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (180, N'Ca un sfârșit definitiv și inevitabil.', 0, 45)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (181, N'Ca o transformare și o prefacere înaintea marelui mister al nemuririi.', 1, 45)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (182, N'Ca un destin implacabil și lipsit de speranță.', 2, 45)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (183, N'Ca un eveniment banal și lipsit de semnificație spirituală.', 3, 45)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (184, N'Universalismul nefondat.', 0, 46)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (185, N'Caracterul prea abstract și normalitatea principiilor rezultate printr-un demers strict deductiv.', 1, 46)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (186, N'Flexibilitatea în abordarea contextului cultural și moral.', 2, 46)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (187, N'Reducționismul.', 3, 46)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (188, N'Concentrarea exclusivă pe aspecte abstracte și normative ale moralității.', 0, 47)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (189, N'Derivarea principiilor din analiza faptelor concrete sau a unor tipuri de comportament.', 1, 47)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (190, N'Ignorarea problemelor complexe și controversate din societate.', 2, 47)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (191, N'Promovarea unei abordări strict deductive în etică.', 3, 47)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (192, N'Eutanasia și etica ecologică.', 0, 48)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (193, N'Discriminarea în rândul animalelor.', 1, 48)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (194, N'Tratamentul preferențial în domeniul industrial.', 2, 48)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (195, N'Demagogia și falsitatea promisiunilor în politica publică.', 3, 48)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (196, N'Lipsa lor de responsabilitate și preocupare pentru binele comun.', 0, 49)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (197, N'Efectul coruptor al rolurilor publice și a restricțiilor personale impuse.', 1, 49)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (198, N'O lipsă generală de cunoștințe etice și morale.', 2, 49)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (199, N'Lipsa unui cadru legal adecvat pentru sancționarea abuzurilor în serviciul public.', 3, 49)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (200, N'O înțelepciune sporită prin excesul de restricții morale.', 0, 50)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (201, N'O îndreptare a omului prin acțiuni etice și cumpătate.', 1, 50)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (202, N'Speranța într-o înțelepțire a omului prin cumpătul cel bun.', 2, 50)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (203, N'O evoluție spre un comportament moral ireproșabil prin introducerea de norme mai stricte.', 3, 50)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (204, N'Nivelul ridicat de cinism acceptabil în viața publică, determinat de instituții.', 0, 51)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (205, N'Dependența moralității publice de trăsăturile morale ale instituțiilor.', 1, 51)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (206, N'Diferențele de aplicare a restricțiilor asupra mijloacelor între viața publică și cea privată.', 2, 51)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (207, N'Simplitatea și uniformitatea moralității în toate aspectele vieții sociale.', 3, 51)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (208, N'Instituțiile publice sunt făcute să servească scopuri mai largi decât cele individuale.', 0, 52)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (209, N'Există o diviziune a muncii atât în executarea, cât și în luarea deciziilor în viața publică.', 1, 52)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (210, N'Trăsăturile morale ale individului nu sunt relevante în viața publică.', 2, 52)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (211, N'Moralitatea publică acordă o importanță mai mare rezultatelor decât cea privată.', 3, 52)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (212, N'Oferă o importanță mai mică rezultatelor și se concentrează mai mult pe mijloace.', 0, 53)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (213, N'Oferă o importanță mai mare rezultatelor, ca urmare a slăbirii anumitor constrângeri centrate pe acțiune.', 1, 53)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (214, N'Are o importanță egală atât pentru rezultate, cât și pentru mijloace.', 2, 53)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (215, N'Este mai preocupată de mijloace decât de rezultate.', 3, 53)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (216, N'Instituțiile publice sunt construite pentru a servi interesele individuale și de familie.', 0, 54)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (217, N'Moralitatea publică poate justifica anumite deviații de la moralitatea privată, în special în ceea ce privește mijloacele folosite.', 1, 54)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (218, N'Toleranța impersonală a moralității publice furnizează un motiv pentru acceptarea individualismului în moralitatea privată.', 2, 54)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (219, N'Există o diviziune morală a muncii între individ și societate, unde idealurile individuale și cele sociale sunt interconectate.', 3, 54)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (220, N'Persoana își dorește să moară, dar nu poate exprima acest lucru în mod activ.', 0, 55)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (221, N'Persoana își dorește să moară și a exprimat această dorință în momentele de luciditate.', 1, 55)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (222, N'Persoana nu își dorește să moară, dar este de acord cu eutanasia în anumite condiții.', 2, 55)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (223, N'Persoana este incapabilă să ia o decizie privind viața sau moartea sa.', 3, 55)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (224, N'Când persoana își dorește să moară, dar nu a exprimat explicit această dorință anterior.', 0, 56)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (225, N'Când persoana nu a fost întrebată niciodată dacă ar accepta eutanasia în anumite circumstanțe.', 1, 56)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (226, N'Când persoana este capabilă să decidă, dar refuză eutanasia și totuși i se aplică.', 2, 56)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (227, N'Când persoana este incapabilă să aleagă între viață și moarte din cauza unei boli incurabile.', 3, 56)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (228, N'Persoana nu își dorește să moară și nu și-a dat niciodată consimțământul.', 0, 57)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (229, N'Persoana este capabilă să ia o decizie, dar nu i s-a cerut consimțământul.', 1, 57)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (230, N'Persoana își dorește să moară și a exprimat acest lucru anterior, dar nu este luat în considerare.', 2, 57)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (231, N'Persoana nu este capabilă să ia o decizie și nu i s-a cerut consimțământul.', 3, 57)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (232, N'Eutanasia activă implică oprirea tratamentului care menține pacientul în viață.', 0, 58)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (233, N'Eutanasia pasivă implică oprirea tratamentului care menține pacientul în viață.', 1, 58)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (234, N'Eutanasia activă este permisă, în timp ce eutanasia pasivă este considerată ilegală.', 2, 58)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (235, N'Eutanasia pasivă este realizată cu consimțământul explicit al pacientului.', 3, 58)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (236, N'Eutanasia voluntară poate fi doar activă, în timp ce eutanasia nevoluntară este întotdeauna pasivă.', 0, 59)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (237, N'Eutanasia involuntară este întotdeauna activă, în timp ce eutanasia pasivă este întotdeauna voluntară.', 1, 59)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (238, N'Toate formele de eutanasie pot fi atât active, cât și pasive.', 2, 59)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (239, N'Eutanasia voluntară și nevoluntară sunt întotdeauna active, în timp ce eutanasia involuntară este întotdeauna pasivă.', 3, 59)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (240, N'Obligația de a promova cel mai bun rezultat global.', 0, 60)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (241, N'Echilibrul între moralitatea orientată spre rezultate și moralitatea orientată spre acțiune.', 1, 60)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (242, N'Lipsa constrângerilor centrate pe agent.', 2, 60)
INSERT INTO [dbo].[Options] ([Id], [Value], [Index], [QuestionId]) VALUES (243, N'Dependența moralității de trăsăturile individuale ale actorilor publici.', 3, 60)
SET IDENTITY_INSERT [dbo].[Options] OFF
