SET IDENTITY_INSERT [dbo].[Questions] ON
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (1, N'Care este concepția lui J. Locke privind fundamentarea moralei?', 1, 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (2, N'Care este opinia lui Friedrich Nietzsche cu privire la ierarhia valorilor morale?', 2, 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (3, N'Cum definește Friedrich Nietzsche omul slab în contextul moralității?', 2, 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (4, N'Ce concluzionează Friedrich Nietzsche în privința modalităților de convertire a oamenilor la moralitate?', 1, 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (5, N'Care este perspectiva lui Blaise Pascal cu privire la capacitatea omului de a obține fericirea?', 3, 1)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (6, N'Ce analogie face John Locke în textul său pentru a ilustra posibilitatea de a deduce regulile morale?', 1, 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (7, N'Care este argumentul lui Locke în sprijinul ideii că moralitatea poate fi tratată ca o știință demonstrabilă?', 0, 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (8, N'Ce concluzie trage Locke în legătură cu relația dintre proprietate și nedreptate?', 1, 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (9, N'Care este ideea principală a pasajului prezentat din textul lui John Locke?', 2, 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (10, N'Care este metoda propusă de Locke pentru examinarea și stabilirea moralității?', 3, 2)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (11, N'Care este perspectiva lui Nietzsche asupra regulilor de bună-cuviință și a egalității între indivizi?', 2, 3)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (12, N'Ce sugerează Nietzsche despre voința de putere în relație cu viața și societatea?', 1, 3)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (13, N'Care este opinia lui Nietzsche despre conceptul de "exploatare" în cadrul societății?', 0, 3)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (14, N'Ce consideră Nietzsche că este factorul primordial al întregii istorii?', 1, 3)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (15, N'Care este concluzia lui Nietzsche în privința exploatării și voinței de putere în societate?', 3, 3)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (16, N'Ce observă Pascal despre natura umană și dorința de fericire?', 1, 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (17, N'Ce observă Pascal despre modurile în care oamenii caută fericirea?', 0, 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (18, N'Ce concluzie trage Pascal cu privire la căutarea fericirii?', 3, 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (19, N'Cum caracterizează Pascal eforturile umane de a găsi adevărul și fericirea?', 0, 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (20, N'Care este tema principală abordată de Pascal în textul dat?', 2, 4)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (21, N'Care este centrul eticii greceşti?', 2, 5)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (22, N'Ce consideră Platon că este suficient pentru fericire?', 2, 5)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (23, N'Care sunt virtuțile cardinale, conform perspectivei lui Platon?', 3, 5)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (24, N'Ce argumentează Aristotel în legătură cu fericirea?', 2, 5)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (25, N'Cum sunt definite virtuţile morale de către Aristotel?', 0, 5)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (26, N'Care este moneda pe care o consideră Socrate drept schimbul cinstit pentru obținerea virtuții?', 1, 6)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (27, N'Ce consideră Socrate că este rezultatul unei purificări de plăceri, dureri și teamă?', 3, 6)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (28, N'Ce compară Socrate cu umbre jucate pe un perete, în absența cunoașterii?', 0, 6)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (29, N'Care este mijlocul de purificare menționat de Socrate?', 1, 6)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (30, N'Ce caracteristică consideră Socrate că are virtutea în lipsa cunoașterii?', 2, 6)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (31, N'Ce reprezintă scopul final al vieții, conform lui Aristotel?', 2, 7)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (32, N'Care este caracteristica esențială a fericirii, conform lui Aristotel?', 3, 7)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (33, N'Ce caracteristică a acțiunilor virtuoase le conferă un caracter de dorit pentru ele însele?', 2, 7)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (34, N'Ce argument aduce Aristotel împotriva ideii că viața fericită ar consta în joc sau glumă?', 2, 7)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (35, N'Care este concluzia lui Aristotel cu privire la viața fericită?', 0, 7)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (36, N'Ce reprezintă viața fericită, conform textului lui Augustin?', 2, 8)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (37, N'Ce concluzie trage Augustin cu privire la dorința oamenilor de a fi înșelați sau de a fi cinstiți?', 1, 8)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (38, N'Ce relație există între viața fericită și adevăr, conform lui Augustin?', 0, 8)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (39, N'Care este motivul pentru care oamenii nu sunt fericiți, conform lui Augustin?', 1, 8)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (40, N'Care este calea spre fericire, potrivit lui Augustin?', 3, 8)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (41, N'Ce reprezintă moartea în contextul creştinismului, conform lui Mircea Eliade?', 1, 9)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (42, N'Ce reprezintă răsturnarea de valori în creştinism?', 2, 9)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (43, N'Care este relația dintre viață și moarte în mesajul creştin, conform lui Mircea Eliade?', 0, 9)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (44, N'Care este sensul dinamic al răsturnării de valori în creştinism, conform lui Mircea Eliade?', 3, 9)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (45, N'Cum este percepută moartea în contextul creştinismului, potrivit lui Mircea Eliade?', 1, 9)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (46, N'Care dintre următoarele aspecte nu este una dintre acuzațiile aduse teoriilor morale telefonice și deontologice?', 2, 10)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (47, N'Ce caracteristică este asociată eticilor aplicate?', 1, 10)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (48, N'Care este una dintre problemele etice majore discutate în spațiul public contemporan?', 3, 10)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (49, N'Ce explică Thomas Nagel în ceea ce privește comportamentul persoanelor în funcții publice?', 1, 10)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (50, N'Care este speranța exprimată de C. Noica în ceea ce privește comportamentul uman?', 2, 10)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (51, N'Care dintre următoarele nu este una dintre obiecțiile aduse de Thomas Nagel teoriilor morale în contextul diferențierii dintre viața publică și cea privată?', 3, 11)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (52, N'Care dintre următoarele nu este un motiv pentru care moralitatea publică și cea privată diferă în aplicare?', 2, 11)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (53, N'Ce importanță acordă moralitatea publică rezultatelor în comparație cu moralitatea privată?', 1, 11)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (54, N'Care dintre următoarele afirmații nu reflectă o idee prezentată de Thomas Nagel?', 0, 11)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (55, N'Care este definiția corectă a eutanasiei voluntare?', 1, 12)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (56, N'În ce situație poate fi considerată eutanasia nevoluntară?', 3, 12)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (57, N'Care este o caracteristică a eutanasiei involuntare conform textului?', 0, 12)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (58, N'Care dintre următoarele afirmații este adevărată în legătură cu diferența dintre eutanasia activă și cea pasivă?', 1, 12)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (59, N'Care este concluzia corectă despre formele de eutanasie?', 2, 12)
INSERT INTO [dbo].[Questions] ([Id], [QuestionText], [CorrectOptionIndex], [Chapter]) VALUES (60, N'Care este o caracteristică distinctivă a moralității publice, conform lui Thomas Nagel?', 1, 11)
SET IDENTITY_INSERT [dbo].[Questions] OFF
